#!/usr/bin/env python3
"""Scrape Google Scholar stats -> _data/scholar.yml. Keep-last-good on any failure."""
import os, sys, datetime, pathlib

PROFILE_URL = os.environ.get(
    "PROFILE_URL",
    "https://scholar.google.com/citations?user=msjTpJQAAAAJ&hl=en")
HEADERS = {
    "User-Agent": ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
                   "AppleWebKit/537.36 (KHTML, like Gecko) "
                   "Chrome/124.0.0.0 Safari/537.36"),
    "Accept-Language": "en-US,en;q=0.9",
}


def parse_stats(html):
    """Return {'citations','h_index','i10'} from the 'All' column, or None if not parseable."""
    if "gsc_rsb_std" not in html:
        return None
    from bs4 import BeautifulSoup
    cells = [c.get_text(strip=True).replace(",", "")
             for c in BeautifulSoup(html, "html.parser").select("td.gsc_rsb_std")]
    if len(cells) < 5:
        return None
    try:
        citations, h_index, i10 = int(cells[0]), int(cells[2]), int(cells[4])
    except ValueError:
        return None
    if not (citations and h_index and i10):
        return None
    return {"citations": citations, "h_index": h_index, "i10": i10}


def _set_output(changed):
    gh = os.environ.get("GITHUB_OUTPUT")
    if gh:
        with open(gh, "a") as fh:
            fh.write(f"changed={'true' if changed else 'false'}\n")


def main():
    import requests
    try:
        r = requests.get(PROFILE_URL, headers=HEADERS, timeout=30)
        stats = parse_stats(r.text) if r.status_code == 200 else None
    except Exception as e:  # network error, etc.
        print(f"::warning::request error: {e}")
        stats = None
    if stats is None:
        print("::warning::Scholar scrape skipped — keeping last good data")
        _set_output(False)
        return 0
    today = datetime.date.today().isoformat()
    pathlib.Path("_data").mkdir(exist_ok=True)
    pathlib.Path("_data/scholar.yml").write_text(
        "# Auto-generated by .github/workflows/scholar.yml — do not edit by hand\n"
        f"citations: {stats['citations']}\n"
        f"h_index: {stats['h_index']}\n"
        f"i10: {stats['i10']}\n"
        f"updated: {today}\n", encoding="utf-8")
    print(f"OK {stats} updated={today}")
    _set_output(True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
